# from https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-latest]
        python-version: ["3.11"]
    steps:
      - name: Get repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff black

      - name: Lint with Ruff
        run: |
          ruff .

      - name: Lint with black
        run: |
          black --check .

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Get repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          # cache-dependency-path: "pyproject.toml"

      - name: Setup Qt libs
        uses: tlambert03/setup-qt-libs@v1

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest-xvfb
          python -m pip install -e .[test]

      - name: Test with pytest
        run: |
          pytest -vv --cov-report xml

      - name: Codecov Upload
        uses: codecov/codecov-action@v2.1.0
        with:
          file: coverage.xml
